# model configuration
model:
  seed: 0
  checkpoint: null  # load weights from checkpoint
  model_class: resnet
  model_params:
    backbone: resnet152
    num_latents: 768  # null is a fully convolutional model, integer value forces bottleneck; matched to SABLE's per-view latent dim
    image_size: 224  # usually 224
    num_channels: 3  # 3 for RGB

# training configuration
training:
  seed: 0
  imgaug: default
  train_batch_size: 24       # per GPU, reduced from base config due to larger model memory footprint
  val_batch_size: 128
  test_batch_size: 32
  num_epochs: 280
  num_workers: 8              # Number of CPU workers for the DataLoader
  num_gpus: 1
  num_nodes: 1
  log_every_n_steps: 10       # frequency to log training metrics
  check_val_every_n_epoch: 5  # frequency to log validation metrics

# optimizer configuration
optimizer:
  type: AdamW
  accumulate_grad_batches: 8  # effective batch size stays 256 (32 * 8)
  lr: 5.e-4
  wd: 0.05
  scheduler: cosine  # {step, cosine}
  warmup_pct: 0.15   # for cosine
  div_factor: 10     # for cosine
  gamma: 0.5         # for step
  steps:             # for step
    - 200
    - 400

# data configuration
data:
  data_dir: /PATH/TO/DATA
  session_names:
    - 9b528ad0-4599-4a55-9148-96cc1d93fb24
    - 51e53aff-1d5d-4182-a684-aba783d50ae5
    - 0802ced5-33a3-405e-8336-b65ebc5cb07c
    - 88224abb-5746-431f-9c17-17d7ef806e6a
    - a4a74102-2af5-45dc-9e41-ef7f5aed88be
    - ecb5520d-1358-434c-95ec-93687ecd1396
    - f312aaec-3b6f-44b3-86b4-3a0c119c0438
